
package com.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CounthouseServerImplService", targetNamespace = "http://server.com/", wsdlLocation = "http://localhost:8080/counthouse?wsdl")
public class CounthouseServerImplService
    extends Service
{

    private final static URL COUNTHOUSESERVERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException COUNTHOUSESERVERIMPLSERVICE_EXCEPTION;
    private final static QName COUNTHOUSESERVERIMPLSERVICE_QNAME = new QName("http://server.com/", "CounthouseServerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/counthouse?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COUNTHOUSESERVERIMPLSERVICE_WSDL_LOCATION = url;
        COUNTHOUSESERVERIMPLSERVICE_EXCEPTION = e;
    }

    public CounthouseServerImplService() {
        super(__getWsdlLocation(), COUNTHOUSESERVERIMPLSERVICE_QNAME);
    }

    public CounthouseServerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COUNTHOUSESERVERIMPLSERVICE_QNAME, features);
    }

    public CounthouseServerImplService(URL wsdlLocation) {
        super(wsdlLocation, COUNTHOUSESERVERIMPLSERVICE_QNAME);
    }

    public CounthouseServerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COUNTHOUSESERVERIMPLSERVICE_QNAME, features);
    }

    public CounthouseServerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CounthouseServerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CounthouseServer
     */
    @WebEndpoint(name = "CounthouseServerImplPort")
    public CounthouseServer getCounthouseServerImplPort() {
        return super.getPort(new QName("http://server.com/", "CounthouseServerImplPort"), CounthouseServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CounthouseServer
     */
    @WebEndpoint(name = "CounthouseServerImplPort")
    public CounthouseServer getCounthouseServerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.com/", "CounthouseServerImplPort"), CounthouseServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COUNTHOUSESERVERIMPLSERVICE_EXCEPTION!= null) {
            throw COUNTHOUSESERVERIMPLSERVICE_EXCEPTION;
        }
        return COUNTHOUSESERVERIMPLSERVICE_WSDL_LOCATION;
    }

}
