
package com.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CounthouseServer", targetNamespace = "http://server.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CounthouseServer {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.server.Response
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://server.com/CounthouseServer/processRequest", output = "http://server.com/CounthouseServer/processResponse")
    public Response process(
        @WebParam(name = "arg0", partName = "arg0")
        Request arg0);

}
